import express from "express";
import { createOrder } from "../controllers/paymentController.js";
import { verifyPayment } from "../controllers/paymentVerificationController.js";
import { handleRazorpayWebhook } from "../controllers/paymentWebhookController.js";
import { handleGetePayCallback, handleGetePayReturn, getGetePayHealth } from "../controllers/getepayController.js";
const router = express.Router();
router.post("/create-order", createOrder);
router.post("/verify", verifyPayment);
router.post("/webhook", handleRazorpayWebhook);
router.post("/getepay/callback", handleGetePayCallback);
router.post("/getepay/return", handleGetePayReturn);
router.get("/getepay/return", handleGetePayReturn);
router.get("/getepay/health", getGetePayHealth);
router.get("/", (req, res) => res.json({ success: true, message: "Payment Route Working" }));
export default router;
